<?php

namespace ClubBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTopEvent()
    {
        $conn=$this->getEntityManager()->getConnection();
        $sql='SELECT  id_event  FROM  
       Reservation r
       GROUP BY id_event
       ORDER BY COUNT(id_event) DESC
       LIMIT 1
       ';
        $stmt=$conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetch();
    }
}
