<?php

namespace CalendrierBundle\Repository;

/**
 * CalenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalenderRepository extends \Doctrine\ORM\EntityRepository
{
}
