<?php

namespace CalendrierBundle\Repository;

use CalendrierBundle\Entity\Calendrier;

/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends \Doctrine\ORM\EntityRepository
{
    public function mfind($id){

$query=$this->getEntityManager()->createQuery("select p from CalendrierBundle:Calendrier p where p.prof=:id  order by p.heure asc 
")
    ->setParameter('id',$id);
return $query->getResult();


    }

    public function findeleve()
    {
        $query=$this->getEntityManager()->createQuery("select p from CalendrierBundle:Calendrier p where p.salle=:id  ")
            ->setParameter('id',$id);
        return $query->getResult();

    }
}
