<?php

namespace CalendrierBundle\Repository;

/**
 * HeureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeureRepository extends \Doctrine\ORM\EntityRepository
{
}
