<?php

namespace CalendrierBundle\Repository;

/**
 * LikePlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikePlatRepository extends \Doctrine\ORM\EntityRepository
{
}
