<?php

namespace CalendrierBundle\Repository;

/**
 * profRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profRepository extends \Doctrine\ORM\EntityRepository
{
}
