<?php

namespace CalendrierBundle\Repository;

/**
 * TTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TTRepository extends \Doctrine\ORM\EntityRepository
{
}
