<?php

namespace SuiviBundle\Repository;

/**
 * ListeAppelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeAppelRepository extends \Doctrine\ORM\EntityRepository
{
    function FindC($id){
        $query=$this->getEntityManager()->createQuery("select la from SuiviBundle:ListeAppel la where la.classe=:idc ")
            ->setParameter('idc',$id);
        return $query->getResult();

    }
    function Finde($ide){
        $query=$this->getEntityManager()->createQuery("select la from SuiviBundle:ListeAppel la where la.eleve=:ide ")
            ->setParameter('ide',$ide);
        return $query->getResult();

    }
}
