club_homepage:
    path:     /home
    defaults: { _controller: ClubBundle:Default:index }

_ajouter:
    path:     /Ajouter
    defaults: { _controller: ClubBundle:Club:Ajouter }

calendar:
    path:     /calendar
    defaults: { _controller: ClubBundle:Club:calendar }

_modifier:
    path:     /Modifier/{id}
    defaults: { _controller: ClubBundle:Club:Modifier }

_afficher:
    path:     /Afficher
    defaults: { _controller: ClubBundle:Club:Afficher }

_supprimer:
    path:     /Supprimer/{id}
    defaults: { _controller: ClubBundle:Club:Supprimer }

_afficherC:
    path:     /Afficher/{id}
    defaults: { _controller: ClubBundle:Club:AfficherId }

_ajouterEvent:
    path:     /AjouterEvent
    defaults: { _controller: ClubBundle:Event:Ajouter }

_modifierEvent:
    path:     /ModifierEvent/{id}
    defaults: { _controller: ClubBundle:Event:Modifier }

_afficherEvent:
    path:     /AfficherEvent
    defaults: { _controller: ClubBundle:Event:Afficher }

_supprimerEvent:
    path:     /SupprimerEvent/{id}
    defaults: { _controller: ClubBundle:Event:Supprimer }

_afficherEventID:
    path:     /AfficherEvent/{id}
    defaults: { _controller: ClubBundle:Event:AfficherEventID }

_reserver:
    path:     /Reserver/{id}
    defaults: { _controller: ClubBundle:Reservation:Reserver }

_sendMail:
    path:     /sendMail/{id}
    defaults: { _controller: ClubBundle:Mail:sendMail }

_afficherEventFront:
    path:     /EventFront
    defaults: { _controller: ClubBundle:Event:AfficherEventFront }

_afficherClubFront:
    path:     /ClubFront
    defaults: { _controller: ClubBundle:Club:AfficherClubFront }
