<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    function FindCl($id){
        $query=$this->getEntityManager()->createQuery("select e from UserBundle:User e where e.classe=:idc")->setParameter('idc',$id);
        return $query->getResult();

    }
   function ChercherNom($nom){
        $query=$this->getEntityManager()->createQuery("select e from UserBundle:User e where e.nom LIKE '%$nom%' and e.roles like :x")
        ->setParameter('x','%a:1:{i:0;s:5:"ELEVE";}%');
        return $query->getResult();

    }
    function findEns(){
        $query=$this->getEntityManager()->createQuery("select e from UserBundle:User e where e.roles like 'a:1:{i:0;s:10:\"ENSEIGNANT\";}' ")
       ;
        return $query->getResult();

    }
    public function findMailEleve(){
        $query=$this->getEntityManager()->createQuery("select e from UserBundle:User e where e.roles like 'a:1:{i:0;s:10:\"ELEVE\";}' ")
        ;
        return $query->getArrayResult();

    }
    public function ChercherNomEns($x){
        $query=$this->getEntityManager()->createQuery("select e from UserBundle:User e where e.nom LIKE '%$x%' and e.roles like :a ")
            ->setParameter('a','%a:1:{i:0;s:10:"ENSEIGNANT";}%');
        return $query->getResult();
    }
}
