<?php

namespace CantineBundle\Repository;

/**
 * AvisNegatifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisNegatifRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findvote($idUser, $plat)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('DELETE FROM CantineBundle:AvisNegatif R WHERE R.plat = :id AND R.ideleve = :ideleve');
        $dql->setParameter(':id',$plat)
            ->setParameter(':ideleve', $idUser)
            ->setMaxResults(1);
        return $dql->getResult();
    }
}
