<?php

namespace CantineBundle\Repository;

/**
 * AvisPlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisPlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindme($user, $plat)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('SELECT R FROM CantineBundle:AvisPlat R WHERE R.plat = :id AND R.ideleve = :ideleve');
        $dql->setParameter(':id',$plat)
            ->setParameter(':ideleve', $user);
        return $dql->getResult();
    }


    public function  findvote($idUser, $plat)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('DELETE FROM CantineBundle:AvisPlat R WHERE R.plat = :id AND R.ideleve = :ideleve');
        $dql->setParameter(':id',$plat)
            ->setParameter(':ideleve', $idUser)
            ->setMaxResults(1);
        return $dql->getResult();
    }

}
