<?php

namespace CantineBundle\Repository;

/**
 * JourdelasemaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourdelasemaineRepository extends \Doctrine\ORM\EntityRepository
{
}
