<?php

namespace CantineBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findnotif($plat)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('DELETE FROM CantineBundle:notification R WHERE R.plat = :id');
        $dql->setParameter(':id',$plat);


        return $dql->getResult();
    }

    public function findNotifExiste($plat,$user)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('SELECT R FROM CantineBundle:notification R WHERE R.plat = :id and R.user = :user');
        $dql->setParameter(':id',$plat);
        $dql->setParameter(':user',$user);
        return $dql->getResult();
    }


}
