<?php

namespace CantineBundle\Repository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTop(){
        $query=$this->getEntityManager()
            ->createQuery("select p from CantineBundle:Plat p order by p.likes desc")
            ->setMaxResults(3);

        return $query->getResult();



    }


    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM CantineBundle:Plat e
                WHERE e.libelle LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

}
