<?php

namespace CoursBundle\Repository;

/**
 * NoteTotalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteTotalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCondition($user,$cours)
    {
        $query = $this->getEntityManager()->createQuery("delete from CoursBundle:NoteTotal e where e.Cours =:ques and e.User=:user")
            ->setParameter('ques',$cours)
            ->setParameter('user',$user)
        ;
        return $query->getResult();
    }
}
