<?php

namespace CoursBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfind($id)
    {
        $query = $this->getEntityManager()->createQuery("select e from CoursBundle:Reponse e where e.Question = '$id'");
        return $query->getResult();
    }
    public function findReponse($q)
    {
        $query = $this->getEntityManager()->createQuery("select e from CoursBundle:Reponse e where e.Question = '$q' ");
        return $query->getResult();
    }
    public function findCorrect($q)
    {
        $query = $this->getEntityManager()->createQuery("select e from CoursBundle:Reponse e where e.id = '$q' ");
        return $query->getResult();
    }
    public function findAllCorrect($q)
    {
        $query=$this->getEntityManager()->createQuery("select  e from CoursBundle:Reponse e where  e.etat like 'Vrai' and e.
        Question ='$q'");
        return $query->getResult();
    }
}
