<?php

namespace CoursBundle\Repository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindMesCours(){
        $query=$this->getEntityManager()->createQuery("select e from CoursBundle:Wish e group by e.cours");
        return $query->getResult();
    }
}
