<?php

namespace RecBundle\Repository;

/**
 * parentrecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parentrecRepository extends \Doctrine\ORM\EntityRepository
{
}
