<?php

namespace RecBundle\Repository;

/**
 * recparentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recparentRepository extends \Doctrine\ORM\EntityRepository
{

}
