<?php

namespace RecEnsBundle\Repository;

/**
 * recensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recensRepository extends \Doctrine\ORM\EntityRepository
{
}
