administration_homepage:
    path:     /home
    defaults: { _controller: AdministrationBundle:Default:index }
administration_ajout:
    path:     /ajout
    defaults: { _controller: AdministrationBundle:Administration:Ajout }

administration_ajout_eleve:
    path:     /AjouterEleve
    defaults: { _controller: AdministrationBundle:Administration:AjouterEleve }
