<?php

namespace SuiviEnsBundle\Repository;

/**
 * SuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends \Doctrine\ORM\EntityRepository
{
    function ChercherNom($nom){
        $query=$this->getEntityManager()->createQuery("select e from SuiviEnsBundle:Suivi e where e.nom LIKE '%$nom%' ")
            ->setParameter('x','%a:1:{i:0;s:5:"ELEVE";}%');
        return $query->getResult();

    }
    public function ChercherNomEns($x){
        $query=$this->getEntityManager()->createQuery("select e from SuiviEnsBundle:Suivi e where e.Ens LIKE '%$x%'  ")
   ;
        return $query->getResult();
    }
}
