<?php

namespace AdministrationBundle\Repository;

/**
 * etudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etudiantRepository extends \Doctrine\ORM\EntityRepository
{
}
